# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdebnMK0Lfi1dh4tceMies4XzYpfSZFx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


data = {
    "YearsExperience": [1.1, 1.3, 1.5, 2.0, 2.2, 2.9, 3.0, 3.2, 3.7, 4.0,
                         4.1, 4.5, 5.1, 5.3, 5.9, 6.0, 6.8, 7.1, 7.9, 8.2,
                         8.7, 9.0, 9.5, 9.6, 10.3, 10.5],
    "Salary": [39343, 46205, 37731, 43525, 39891, 56642, 60150, 54445,
               57189, 63218, 55794, 61111, 67938, 66029, 83088, 81363,
               93940, 98273, 101302, 113812, 109431, 105582, 116969,
               112635, 122391, 121872]
}
df = pd.DataFrame(data)
print("First 5 rows of dataset:")
print(df.head())


X = df[["YearsExperience"]]
y = df["Salary"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


model = LinearRegression()
model.fit(X_train, y_train)

print(f"\nModel Coefficient (slope): {model.coef_[0]:.2f}")
print(f"Model Intercept: {model.intercept_:.2f}")


y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"\nMean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")


plt.figure(figsize=(8, 5))
plt.scatter(X_train, y_train, color="blue", label="Training data")
plt.scatter(X_test, y_test, color="green", label="Test data")
plt.plot(X, model.predict(X), color="red", label="Regression line")
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.title("Salary vs Years of Experience (Linear Regression)")
plt.legend()
plt.tight_layout()
plt.savefig("salary_regression_plot.png", dpi=150)
print("\nPlot saved as salary_regression_plot.png")


years = 6.5
predicted_salary = model.predict([[years]])
print(f"\nPredicted salary for {years} years experience: {predicted_salary[0]:.2f}")