# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdebnMK0Lfi1dh4tceMies4XzYpfSZFx
"""

!pip install -q xgboost lightgbm shap

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

import xgboost as xgb
import lightgbm as lgb
import shap

sns.set(style="whitegrid")

columns = [
    "age", "sex", "cp", "trestbps", "chol", "fbs", "restecg",
    "thalach", "exang", "oldpeak", "slope", "ca", "thal", "target"
]

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

df = pd.read_csv(
    url,
    names=columns,
    na_values="?"
)

df = df.dropna()
df["target"] = (df["target"] > 0).astype(int)

X = df.drop(columns=["target"])
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

xgb_model = xgb.XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.1,
    eval_metric="logloss",
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)
y_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]

print("=== XGBoost Results ===")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("ROC-AUC :", roc_auc_score(y_test, y_proba_xgb))
print(classification_report(y_test, y_pred_xgb))

lgb_model = lgb.LGBMClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.1,
    random_state=42
)

lgb_model.fit(X_train, y_train)

y_pred_lgb = lgb_model.predict(X_test)
y_proba_lgb = lgb_model.predict_proba(X_test)[:, 1]

print("\n=== LightGBM Results ===")
print("Accuracy:", accuracy_score(y_test, y_pred_lgb))
print("ROC-AUC :", roc_auc_score(y_test, y_proba_lgb))
print(classification_report(y_test, y_pred_lgb))

comparison = pd.DataFrame({
    "Model": ["XGBoost", "LightGBM"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_xgb),
        accuracy_score(y_test, y_pred_lgb)
    ],
    "ROC-AUC": [
        roc_auc_score(y_test, y_proba_xgb),
        roc_auc_score(y_test, y_proba_lgb)
    ]
})

print("\nModel Comparison:\n", comparison)

explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(
    shap_values,
    X_test,
    show=True
)

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar",
    show=True
)

shap.initjs()

sample_idx = 0

shap.force_plot(
    explainer.expected_value,
    shap_values[sample_idx, :],
    X_test.iloc[sample_idx, :],
    matplotlib=True
)

plt.show()

top_feature = X.columns[
    np.argmax(np.abs(shap_values).mean(axis=0))
]

shap.dependence_plot(
    top_feature,
    shap_values,
    X_test,
    show=True
)