# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdebnMK0Lfi1dh4tceMies4XzYpfSZFx
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

sns.set(style="whitegrid")

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
df = pd.read_csv(url, sep=";")

print("Shape:", df.shape)
df.head()

print(df.describe())
print("\nQuality value counts:\n", df["quality"].value_counts().sort_index())

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="quality")
plt.title("Wine Quality Score Distribution")
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

def quality_to_class(q):
    if q <= 4:
        return "Low"
    elif q <= 6:
        return "Medium"
    else:
        return "High"

df["quality_class"] = df["quality"].apply(quality_to_class)
print("\nClass distribution:\n", df["quality_class"].value_counts())

plt.figure(figsize=(5, 4))
sns.countplot(data=df, x="quality_class", order=["Low", "Medium", "High"])
plt.title("Wine Quality Class Distribution")
plt.show()

X = df.drop(columns=["quality", "quality_class"])
y = df["quality_class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

dt_model = DecisionTreeClassifier(max_depth=6, random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("=== Decision Tree ===")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("=== Random Forest ===")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
labels = ["Low", "Medium", "High"]

cm_dt = confusion_matrix(y_test, y_pred_dt, labels=labels)
sns.heatmap(
    cm_dt,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=labels,
    yticklabels=labels,
    ax=axes[0]
)
axes[0].set_title("Decision Tree")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

cm_rf = confusion_matrix(y_test, y_pred_rf, labels=labels)
sns.heatmap(
    cm_rf,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=labels,
    yticklabels=labels,
    ax=axes[1]
)
axes[1].set_title("Random Forest")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")

plt.tight_layout()
plt.show()

importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Decision_Tree": dt_model.feature_importances_,
    "Random_Forest": rf_model.feature_importances_
}).sort_values("Random_Forest", ascending=False)

print("\nFeature Importance Comparison:\n", importance_df)

importance_df.set_index("Feature").plot(kind="barh", figsize=(8, 6))
plt.title("Feature Importance: Decision Tree vs Random Forest")
plt.gca().invert_yaxis()
plt.show()

print(f"\nDecision Tree Accuracy : {accuracy_score(y_test, y_pred_dt):.4f}")
print(f"Random Forest Accuracy : {accuracy_score(y_test, y_pred_rf):.4f}")