# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdebnMK0Lfi1dh4tceMies4XzYpfSZFx
"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

df = sns.load_dataset("titanic")
print("Original shape:", df.shape)

df["family_size"] = df["sibsp"] + df["parch"] + 1
df["is_alone"] = (df["family_size"] == 1).astype(int)

drop_cols = ["alive", "deck", "who", "adult_male", "embark_town", "class", "sibsp", "parch"]
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

print("Shape after dropping redundant columns:", df.shape)
print(df.isnull().sum())

target_col = "survived"
X = df.drop(columns=[target_col])
y = df[target_col]

numeric_features = ["age", "fare", "family_size", "pclass"]
categorical_features = ["sex", "embarked", "is_alone"]

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", drop="if_binary"))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

X_processed = preprocessor.fit_transform(X)

cat_feature_names = preprocessor.named_transformers_["cat"]["onehot"].get_feature_names_out(categorical_features)
all_feature_names = numeric_features + list(cat_feature_names)

X_processed_df = pd.DataFrame(
    X_processed.toarray() if hasattr(X_processed, "toarray") else X_processed,
    columns=all_feature_names
)

X_processed_df[target_col] = y.values

print("Processed shape:", X_processed_df.shape)
X_processed_df.head()

output_path = "titanic_cleaned.csv"
X_processed_df.to_csv(output_path, index=False)
print(f"Cleaned dataset saved to: {output_path}")

from google.colab import files
files.download(output_path)