# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdebnMK0Lfi1dh4tceMies4XzYpfSZFx
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")

columns = [
    "age", "workclass", "fnlwgt", "education", "education_num",
    "marital_status", "occupation", "relationship", "race", "sex",
    "capital_gain", "capital_loss", "hours_per_week", "native_country", "income"
]

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
df = pd.read_csv(url, names=columns, na_values=" ?", skipinitialspace=True)

print("Shape:", df.shape)
df.head()

print("Missing values:\n", df.isnull().sum())

df = df.dropna()

df["income"] = df["income"].str.strip().str.replace(".", "", regex=False)

print("Shape after cleaning:", df.shape)

plt.figure(figsize=(5, 4))
sns.countplot(data=df, x="income")
plt.title("Income Class Distribution")
plt.show()

numeric_cols = ["age", "hours_per_week", "capital_gain", "capital_loss"]
df[numeric_cols].hist(figsize=(10, 8), bins=30)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
sns.countplot(
    data=df,
    y="education",
    hue="income",
    order=df["education"].value_counts().index
)
plt.title("Income by Education Level")
plt.show()

plt.figure(figsize=(5, 4))
sns.countplot(data=df, x="sex", hue="income")
plt.title("Income Distribution by Sex")
plt.show()

plt.figure(figsize=(7, 5))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap (Numeric Features)")
plt.show()

df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 35, 45, 55, 65, 100],
    labels=["<25", "25-34", "35-44", "45-54", "55-64", "65+"]
)

df["has_capital_gain"] = (df["capital_gain"] > 0).astype(int)
df["has_capital_loss"] = (df["capital_loss"] > 0).astype(int)

df["is_married"] = df["marital_status"].str.contains("Married").astype(int)

df["work_hours_category"] = pd.cut(
    df["hours_per_week"],
    bins=[0, 20, 40, 60, 100],
    labels=["part_time", "full_time", "over_time", "extreme"]
)

print(
    df[
        [
            "age",
            "age_group",
            "has_capital_gain",
            "is_married",
            "work_hours_category"
        ]
    ].head()
)

plt.figure(figsize=(7, 4))
sns.barplot(
    data=df,
    x="age_group",
    y=(df["income"] == ">50K").astype(int)
)
plt.ylabel("Proportion earning >50K")
plt.title("Income >50K Rate by Age Group")
plt.show()

df.to_csv("adult_income_engineered.csv", index=False)
print("Engineered dataset saved as adult_income_engineered.csv")