# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdebnMK0Lfi1dh4tceMies4XzYpfSZFx
"""

# ==========================================================
# Project 6: Diabetes Severity — Multinomial Logistic
#             Regression Project
# ==========================================================

# %% 1. Imports
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

sns.set(style="whitegrid")

# %% 2. Load dataset
# sklearn's diabetes dataset target = disease progression score (continuous, 25-346)
data = load_diabetes(as_frame=True)
df = data.frame
print("Shape:", df.shape)
df.head()

# %% 3. Convert continuous target into 3 severity classes
# Low / Medium / High severity using quantile-based binning
df["severity"] = pd.qcut(df["target"], q=3, labels=["Low", "Medium", "High"])
print(df["severity"].value_counts())

plt.figure(figsize=(5, 4))
sns.countplot(data=df, x="severity", order=["Low", "Medium", "High"])
plt.title("Diabetes Severity Class Distribution")
plt.show()

# %% 4. EDA — feature correlation with target
plt.figure(figsize=(8, 6))
sns.heatmap(df.drop(columns=["severity"]).corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# %% 5. Train-test split
X = df.drop(columns=["target", "severity"])
y = df["severity"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# %% 6. Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# %% 7. Multinomial Logistic Regression
model = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    max_iter=1000,
    random_state=42
)
model.fit(X_train_scaled, y_train)

# %% 8. Predictions and Evaluation
y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# %% 9. Confusion Matrix
cm = confusion_matrix(y_test, y_pred, labels=["Low", "Medium", "High"])
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Low", "Medium", "High"],
            yticklabels=["Low", "Medium", "High"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix — Multinomial Logistic Regression")
plt.show()

# %% 10. Predicted probabilities for each class (first 5 test samples)
proba_df = pd.DataFrame(model.predict_proba(X_test_scaled[:5]), columns=model.classes_)
print("\nSample predicted class probabilities:\n", proba_df)

# %% 11. Feature importance (coefficients per class)
coef_df = pd.DataFrame(model.coef_, columns=X.columns, index=model.classes_)
print("\nCoefficients per severity class:\n", coef_df)