# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1isN-xR5FxdZ2DA85S3VGRjDbnmAjEbSZ
"""

# Train Ridge, Lasso, and Elastic Net on scaled data
ridge = Ridge(alpha=1.0)
ridge.fit(X_train_scaled, y_train)

lasso = Lasso(alpha=0.01)
lasso.fit(X_train_scaled, y_train)

elastic = ElasticNet(alpha=0.01, l1_ratio=0.5)
elastic.fit(X_train_scaled, y_train)

# Build comparison DataFrame
comparison = pd.DataFrame({
    "Feature": X.columns,
    "Linear Regression": lr.coef_,
    "Ridge": ridge.coef_,
    "Lasso": lasso.coef_,
    "Elastic Net": elastic.coef_
})

print("=" * 60)
print(comparison.to_string(index=True))