# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fTh3cmKMndZ3mLe_KHFYQ9gkveWg2s9
"""

# ==========================================
# MULTIVARIATE ANALYSIS
# ==========================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


# ==========================================
# 1. Load Dataset
# ==========================================

# If df is already loaded, this will use it.
# Otherwise, it will ask you to upload the CSV.

if "df" not in globals():
    from google.colab import files

    uploaded = files.upload()
    filename = list(uploaded.keys())[0]

    df = pd.read_csv(filename)

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

display(df.head())


# ==========================================
# 2. Correlation Heatmap
# ==========================================

plt.figure(figsize=(12, 8))

# Select all numeric columns
numeric_df = df.select_dtypes(include="number")

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()


# ==========================================
# 3. Pair Plot
# ==========================================

pair_columns = [
    "CGPA",
    "AttendancePercent",
    "CodingTestScore",
    "AptitudeTestScore",
    "PlacementStatus"
]

# Check whether required columns exist
missing_columns = [col for col in pair_columns if col not in df.columns]

if missing_columns:
    print("\nMissing columns:", missing_columns)
else:
    sns.pairplot(
        df[pair_columns].dropna(),
        hue="PlacementStatus"
    )

    plt.show()


# ==========================================
# 4. Completion Message
# ==========================================

print("\nEDA Completed Successfully!")