# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLOmxBtWrOysDiDQZVpwF4gyvX_4ZwGp
"""

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


# -----------------------------------
# 1. Load California Housing Dataset
# -----------------------------------

housing = fetch_california_housing(as_frame=True)

df = housing.frame

print("Dataset:")
print(df.head())


# -----------------------------------
# 2. Separate X and Y
# -----------------------------------

X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]


# -----------------------------------
# 3. Train-Test Split
# 80% Training, 20% Testing
# -----------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining data:", X_train.shape)
print("Testing data:", X_test.shape)


# -----------------------------------
# 4. Linear Regression
# -----------------------------------

lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)


# -----------------------------------
# 5. Evaluate Linear Regression
# -----------------------------------

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("\n--- Linear Regression ---")
print("RMSE:", rmse_lr)
print("MAE :", mae_lr)
print("R2  :", r2_lr)


# -----------------------------------
# 6. Coefficients
# -----------------------------------

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": lr.coef_
})

print("\n--- Coefficients ---")
print(coefficients)


# -----------------------------------
# 7. Standardization
# -----------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nData scaling completed.")


# -----------------------------------
# 8. Ridge Regression
# -----------------------------------

ridge = Ridge(alpha=1.0)

ridge.fit(X_train_scaled, y_train)

y_pred_ridge = ridge.predict(X_test_scaled)

rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("\n--- Ridge Regression ---")
print("RMSE:", rmse_ridge)
print("MAE :", mae_ridge)
print("R2  :", r2_ridge)


# -----------------------------------
# 9. Lasso Regression
# -----------------------------------

lasso = Lasso(alpha=0.001)

lasso.fit(X_train_scaled, y_train)

y_pred_lasso = lasso.predict(X_test_scaled)

rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred_lasso))
mae_lasso = mean_absolute_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("\n--- Lasso Regression ---")
print("RMSE:", rmse_lasso)
print("MAE :", mae_lasso)
print("R2  :", r2_lasso)


# -----------------------------------
# 10. Elastic Net Regression
# -----------------------------------

elastic = ElasticNet(alpha=0.001, l1_ratio=0.5)

elastic.fit(X_train_scaled, y_train)

y_pred_elastic = elastic.predict(X_test_scaled)

rmse_elastic = np.sqrt(mean_squared_error(y_test, y_pred_elastic))
mae_elastic = mean_absolute_error(y_test, y_pred_elastic)
r2_elastic = r2_score(y_test, y_pred_elastic)

print("\n--- Elastic Net Regression ---")
print("RMSE:", rmse_elastic)
print("MAE :", mae_elastic)
print("R2  :", r2_elastic)


# -----------------------------------
# 11. Compare Models
# -----------------------------------

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge",
        "Lasso",
        "Elastic Net"
    ],
    "RMSE": [
        rmse_lr,
        rmse_ridge,
        rmse_lasso,
        rmse_elastic
    ],
    "MAE": [
        mae_lr,
        mae_ridge,
        mae_lasso,
        mae_elastic
    ],
    "R2": [
        r2_lr,
        r2_ridge,
        r2_lasso,
        r2_elastic
    ]
})

print("\n--- Model Comparison ---")
print(results)


# -----------------------------------
# 12. Actual vs Predicted Plot
# -----------------------------------

plt.scatter(y_test, y_pred_lr)

plt.xlabel("Actual House Value")
plt.ylabel("Predicted House Value")
plt.title("Actual vs Predicted - Linear Regression")

plt.show()