# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjL-eo9QSqdL7AD3tMNc6ogAUh-120gf
"""

plt.figure(figsize=(6,4))
sns.countplot(data=df,x="PlacementStatus")
plt.title("Placement Status Distribution")
plt.show()