# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejJpiu2ffzwBJAJ4YQbTh2DAWyfFCwuR
"""

# ==========================================
# BIVARIATE ANALYSIS
# ==========================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files


# ==========================================
# 1. Upload CSV File
# ==========================================

uploaded = files.upload()

# Get uploaded file name automatically
filename = list(uploaded.keys())[0]

# Read CSV
df = pd.read_csv(filename)

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

print("File loaded successfully!")
print("File name:", filename)

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())


# ==========================================
# 2. Scatter Plot
# CGPA vs Attendance
# ==========================================

plt.figure(figsize=(6, 4))

sns.scatterplot(
    data=df,
    x="CGPA",
    y="AttendancePercent"
)

plt.title("CGPA vs Attendance Percentage")
plt.xlabel("CGPA")
plt.ylabel("Attendance Percentage")

plt.show()


# ==========================================
# 3. Regression Plot
# CGPA vs Coding Test Score
# ==========================================

plt.figure(figsize=(6, 4))

sns.regplot(
    data=df,
    x="CGPA",
    y="CodingTestScore"
)

plt.title("CGPA vs Coding Test Score")
plt.xlabel("CGPA")
plt.ylabel("Coding Test Score")

plt.show()


# ==========================================
# 4. Box Plot
# CGPA vs Placement Status
# ==========================================

plt.figure(figsize=(6, 4))

sns.boxplot(
    data=df,
    x="PlacementStatus",
    y="CGPA"
)

plt.title("CGPA vs Placement Status")
plt.xlabel("Placement Status")
plt.ylabel("CGPA")

plt.show()


# ==========================================
# 5. Violin Plot
# Attendance vs Placement Status
# ==========================================

plt.figure(figsize=(6, 4))

sns.violinplot(
    data=df,
    x="PlacementStatus",
    y="AttendancePercent"
)

plt.title("Attendance vs Placement Status")
plt.xlabel("Placement Status")
plt.ylabel("Attendance Percentage")

plt.show()


# ==========================================
# 6. Gender vs Placement
# ==========================================

plt.figure(figsize=(6, 4))

sns.countplot(
    data=df,
    x="Gender",
    hue="PlacementStatus"
)

plt.title("Gender vs Placement Status")
plt.xlabel("Gender")
plt.ylabel("Number of Students")

plt.show()


# ==========================================
# 7. Stream vs Placement
# ==========================================

plt.figure(figsize=(10, 5))

sns.countplot(
    data=df,
    x="Stream",
    hue="PlacementStatus"
)

plt.xticks(rotation=45)

plt.title("Stream vs Placement Status")
plt.xlabel("Stream")
plt.ylabel("Number of Students")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
Load Dataset
df = pd.read_csv("placement_predict_50k Dataset.csv")
#Dataset Overview
print(df.head())
print(df.tail())
print(df.shape)
print(df.info())
print(df.describe())
print(df.columns.tolist())
print(df.sample(5))
print(df.nunique())