# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zYgAPXsGSD_xzwwlOFEO1Du4-BXbHuh
"""

# ==========================================
# IMPORT LIBRARIES
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# ==========================================
# LOAD DATASET
# ==========================================

from google.colab import files

uploaded = files.upload()

# Automatically get the uploaded file name
filename = list(uploaded.keys())[0]

# Read the CSV file
df = pd.read_csv(filename)

print("Dataset loaded successfully!")
print("File:", filename)


# ==========================================
# DATASET OVERVIEW
# ==========================================

# First 5 rows
print("\n--- First 5 Rows ---")
print(df.head())


# Last 5 rows
print("\n--- Last 5 Rows ---")
print(df.tail())


# Dataset shape
print("\n--- Dataset Shape ---")
print(df.shape)


# Dataset information
print("\n--- Dataset Information ---")
df.info()


# Statistical description
print("\n--- Statistical Description ---")
print(df.describe())


# Column names
print("\n--- Column Names ---")
print(df.columns.tolist())


# Random 5 rows
print("\n--- Random 5 Rows ---")
print(df.sample(5))


# Number of unique values in each column
print("\n--- Unique Values ---")
print(df.nunique())