# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKDTW2JF8YATs9kpm-RgV8Bvf85-3eEv
"""

a=5
b=6
c=7
print(a+b)

x = 5.5
y = 8.001234567
c = 'h'
s = "hello"

l = [5.5, 8.123, 'x', "welcome"]
l.append(10)
print(l)

l.pop()
print(l)

t = (5.5, 8.123, 'x', "welcome")  # tuple

d = {"a": "apple", "color": ["red", "orange", "blue"], "name": "ravi"}  # dictionary
print(d)

def add(x, y):
    print("hello")
    z = x + y
    return z

result = add(2, 4)
print(result)

class A:
  print("hi")
  def add():
    print("add")

a=A()
A.add()

for i in range(5):
  print(i)
  for j in range(-1,-5):
    print(j)

while(i<5):
  i=i+1
  print(i)

a=5
b=6
c=7
if(a>b):