# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjYEI8yifNVqt77rPBE_ghQ43FbLL8UW
"""

import pandas as pd
import seaborn as sn
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

# --------------------------------
# 1. Create homeprices.csv
# --------------------------------

data = {
    "area": [2600, 3000, 3200, 3600, 4000],
    "price": [550000, 565000, 610000, 680000, 725000]
}

df = pd.DataFrame(data)
df.to_csv("homeprices.csv", index=False)

# --------------------------------
# 2. Read the CSV file
# --------------------------------

df = pd.read_csv("homeprices.csv")

print("Dataset:")
print(df)

# --------------------------------
# 3. Scatter Plot
# --------------------------------

sn.scatterplot(data=df, x="area", y="price")
plt.xlabel("Area (sq.ft.)")
plt.ylabel("Price")
plt.title("Area vs Price")
plt.show()

# --------------------------------
# 4. Create Linear Regression Model
# --------------------------------

reg = LinearRegression()

# --------------------------------
# 5. Train the Model
# --------------------------------

reg.fit(df[["area"]], df["price"])

# --------------------------------
# 6. Predict Price for 3300 sq.ft.
# --------------------------------

prediction_3300 = reg.predict(pd.DataFrame({"area": [3300]}))

print("\nPrice for 3300 sq.ft.:", prediction_3300[0])

# --------------------------------
# 7. Slope and Intercept
# --------------------------------

print("Slope:", reg.coef_[0])
print("Intercept:", reg.intercept_)

# --------------------------------
# 8. Manual Calculation
# --------------------------------

y = reg.coef_[0] * 3300 + reg.intercept_

print("Manual Prediction for 3300 sq.ft.:", y)

# --------------------------------
# 9. Predict Price for 5000 sq.ft.
# --------------------------------

prediction_5000 = reg.predict(pd.DataFrame({"area": [5000]}))

print("Price for 5000 sq.ft.:", prediction_5000[0])

# --------------------------------
# 10. R² Score
# --------------------------------

y_original = df["price"]
y_predict = reg.predict(df[["area"]])

R_square = r2_score(y_original, y_predict)

print("R² Score:", R_square)

# --------------------------------
# 11. Regression Line
# --------------------------------

sn.lmplot(data=df, x="area", y="price")

plt.xlabel("Area (sq.ft.)")
plt.ylabel("Price")
plt.title("Linear Regression")
plt.show()